"use client";

import React, { useState } from "react";
import Link from "next/link";

const RAW_CADS_JSON = `{
  "$schema": "https://cads-standard.org/schema/v2.4.json",
  "parcel_id": "IND-GJ-AMD-2024-0089",
  "timestamp": "2025-11-28T05:30:00Z",
  "coordinates": [23.0225, 72.5714],
  "crop": {
    "type": "wheat",
    "stage": "tillering",
    "ndvi_mean": 0.712
  },
  "observations": {
    "sentinel2_tile": "T43QDA",
    "root_zone_moisture": 0.284,
    "ecmwf_48h_precip_mm": 18.2
  },
  "decision": {
    "primary_action": "DELAY_IRRIGATION",
    "delay_window_hours": 48,
    "water_conserved_litres": 42000,
    "confidence": 0.994,
    "reasoning_trace": [
      "Rain event > 15mm expected within 48h (p=0.82)",
      "HWSD loamy clay water buffer capacity exceeds 48h ET0 loss"
    ]
  }
}`;

export default function NetworkPage() {
  const [copied, setCopied] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3200);
  };

  const handleCopyJson = () => {
    navigator.clipboard?.writeText(RAW_CADS_JSON);
    setCopied(true);
    showToast("CADS v2.4 JSON schema copied to clipboard");
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="space-y-8">
      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed bottom-20 right-6 bg-[var(--ink)] text-[var(--bg)] px-5 py-3 rounded-full text-sm shadow-xl z-50 animate-bounce">
          {toastMessage}
        </div>
      )}

      {/* Page Header */}
      <div className="border-b border-[var(--line)] pb-6 pt-4">
        <div className="wrap">
          <h1 className="text-[2rem] sm:text-[2.6rem] font-medium leading-tight text-[var(--ink)]">
            Common Agricultural Decision Schema (CADS)
          </h1>
          <p className="text-[var(--muted)] text-[1.05rem] mt-1 max-w-2xl">
            A vendor-neutral, explainable agricultural protocol establishing open digital sovereignty for smallholders worldwide.
          </p>
        </div>
      </div>

      <div className="wrap">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
          {/* Left: Overview & Principles */}
          <div className="space-y-5 text-left">
            <div>
              <h2 className="text-[1.8rem] font-medium text-[var(--ink)] mb-2.5">
                Open Machine Contract
              </h2>
              <p className="text-[var(--muted)] text-[0.95rem] leading-relaxed">
                Every recommendation generated by AgriN is serialized in transparent CADS v2.4 JSON format. Any open-source tractor GPS, SMS gateway (Kisan Call Center), or irrigation controller can ingest this payload directly without licensing fees.
              </p>
            </div>

            <div className="card-tmpl">
              <h4 className="text-[1rem] font-medium text-[var(--ink)] mb-2">
                Three Core Principles of CADS:
              </h4>
              <ul className="space-y-2 text-[0.88rem] text-[var(--muted)] leading-relaxed list-disc pl-5">
                <li>
                  <strong className="text-[var(--ink)]">Provenance Traceability:</strong> Raw satellite pixel bounds and numerical weather station coordinates are permanently bound to the advice.
                </li>
                <li>
                  <strong className="text-[var(--ink)]">No Proprietary Lock-in:</strong> Fully compatible with OGC (Open Geospatial Consortium) GeoJSON standards and STAC (SpatioTemporal Asset Catalog).
                </li>
                <li>
                  <strong className="text-[var(--ink)]">Explainable Fallbacks:</strong> If AI inference models are unreachable, deterministic rule tables ensure life-safety irrigation advice is still delivered.
                </li>
              </ul>
            </div>

            <div className="flex gap-3">
              <button
                type="button"
                onClick={handleCopyJson}
                className="btn-tmpl btn-tmpl-primary btn-tmpl-sm text-xs"
              >
                {copied ? "✓ Copied Schema" : "Copy Raw CADS Payload"}
              </button>
              <button
                type="button"
                onClick={() => showToast("cURL test command copied to clipboard")}
                className="btn-tmpl btn-tmpl-ghost btn-tmpl-sm text-xs"
              >
                Test cURL API Sandbox
              </button>
            </div>
          </div>

          {/* Right: Code Box */}
          <div>
            <div className="flex justify-between items-center mb-2 font-mono text-xs">
              <span className="text-[var(--muted)]">
                payload_ahmedabad_wheat_2025.json
              </span>
              <span className="text-[var(--leaf)] font-semibold">
                Valid CADS v2.4
              </span>
            </div>

            <pre className="bg-[#0D1611] text-[#D7EAD7] font-mono text-[0.85rem] p-5 sm:p-6 rounded-[12px] overflow-x-auto border border-[#1C3826] max-h-[480px] leading-relaxed shadow-md">
              <code>{RAW_CADS_JSON}</code>
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
