import { NetworkNode } from "@/types/network";

export const BRICS_NODES: NetworkNode[] = [
  {
    id: "india-ahmedabad",
    country: "India",
    countryCode: "IN",
    flag: "🇮🇳",
    institutionalAnchor: "ICAR (Indian Council of Agricultural Research)",
    location: "Ahmedabad, Gujarat",
    crop: "Wheat (Triticum aestivum)",
    area: "2.5 Acres",
    crs: "EPSG:4326 (WGS 84)",
    satellite: "Copernicus Sentinel-2 MSI Level-2A",
    soilRef: "HWSD v2.0 Standard Profile",
    status: "Synchronized",
    latencyMs: 38,
    lastSync: "Just now",
    complianceScorePct: 100,
    cadsPacket: {
      $schema: "https://agrin.org/schema/v1/cads.json",
      schema_version: "CADS-v1.0.4",
      node_id: "IN-GJ-AHM-0042",
      node_country: "India",
      institutional_anchor: "ICAR Regional Agronomy Center",
      cadastral_crs: "EPSG:4326",
      geographic_reference: {
        district: "Ahmedabad",
        state_province: "Gujarat",
        coordinates: { latitude: 23.0225, longitude: 72.5714 },
        epsg_code: 4326,
      },
      crop_profile: {
        species: "Wheat",
        botanical_name: "Triticum aestivum",
        phenological_stage: "Tillering / Crown Root Initiation",
        area: 2.5,
        area_unit: "Acres",
      },
      telemetry: {
        meteorological: {
          source: "Open-Meteo / IMD Ensemble",
          temperature_c: 28.5,
          rainfall_48h_mm: 18.0,
          et0_daily_mm: 3.2,
          relative_humidity_pct: 64,
        },
        earth_observation: {
          platform: "Sentinel-2 MSI BOA",
          current_ndvi: 0.71,
          canopy_trend: "declining",
          observation_timestamp: "2026-09-28T05:42:10Z",
        },
        soil_chemistry: {
          standard: "HWSD v2.0 Normalization",
          ph: 6.8,
          organic_carbon_pct: 0.54,
          nitrogen_kg_ha: 180,
          soil_texture_class: "Sandy Loam",
        },
      },
      inferred_signals: {
        vegetation_stress: "moderate",
        irrigation_demand: "delay",
        regenerative_horizon: "STAGE 1: Retain moisture & delay pumping 48h",
      },
    },
  },
  {
    id: "brazil-matogrosso",
    country: "Brazil",
    countryCode: "BR",
    flag: "🇧🇷",
    institutionalAnchor: "EMBRAPA (Empresa Brasileira de Pesquisa Agropecuária)",
    location: "Sorriso, Mato Grosso",
    crop: "Soybean (Glycine max)",
    area: "1,200 Hectares",
    crs: "SIRGAS 2000 (EPSG:4674)",
    satellite: "CBERS-4A + Sentinel-2 MSI",
    soilRef: "Embrapa Solos Latosol Profile",
    status: "Synchronized",
    latencyMs: 74,
    lastSync: "3 mins ago",
    complianceScorePct: 100,
    cadsPacket: {
      $schema: "https://agrin.org/schema/v1/cads.json",
      schema_version: "CADS-v1.0.4",
      node_id: "BR-MT-SOR-8190",
      node_country: "Brazil",
      institutional_anchor: "Embrapa Agrossilvipastoril",
      cadastral_crs: "EPSG:4674",
      geographic_reference: {
        district: "Sorriso",
        state_province: "Mato Grosso",
        coordinates: { latitude: -12.5422, longitude: -55.7211 },
        epsg_code: 4674,
      },
      crop_profile: {
        species: "Soybean",
        botanical_name: "Glycine max",
        phenological_stage: "Pod Development (R3-R4)",
        area: 1200,
        area_unit: "Hectares",
      },
      telemetry: {
        meteorological: {
          source: "INMET / Open-Meteo",
          temperature_c: 31.2,
          rainfall_48h_mm: 4.2,
          et0_daily_mm: 4.6,
          relative_humidity_pct: 72,
        },
        earth_observation: {
          platform: "CBERS-4A + Sentinel-2",
          current_ndvi: 0.82,
          canopy_trend: "stable",
          observation_timestamp: "2026-09-27T14:15:00Z",
        },
        soil_chemistry: {
          standard: "Embrapa Latossolo Vermelho",
          ph: 5.6,
          organic_carbon_pct: 1.82,
          nitrogen_kg_ha: 310,
          soil_texture_class: "Clayey Oxisol",
        },
      },
      inferred_signals: {
        vegetation_stress: "low",
        irrigation_demand: "normal",
        regenerative_horizon: "STAGE 2: Direct seeding mulch maintenance (No-Till)",
      },
    },
  },
  {
    id: "southafrica-freestate",
    country: "South Africa",
    countryCode: "ZA",
    flag: "🇿🇦",
    institutionalAnchor: "ARC (Agricultural Research Council)",
    location: "Free State Grain Corridor",
    crop: "White Maize (Zea mays)",
    area: "60 Hectares",
    crs: "Hartebeesthoek94 (EPSG:4148)",
    satellite: "Sentinel-2 + Landsat-9",
    soilRef: "ARC-ISCW Soil Database",
    status: "Synchronized",
    latencyMs: 91,
    lastSync: "6 mins ago",
    complianceScorePct: 100,
    cadsPacket: {
      $schema: "https://agrin.org/schema/v1/cads.json",
      schema_version: "CADS-v1.0.4",
      node_id: "ZA-FS-BLM-0211",
      node_country: "South Africa",
      institutional_anchor: "ARC Smallholder Extension",
      cadastral_crs: "EPSG:4148",
      geographic_reference: {
        district: "Mangaung",
        state_province: "Free State",
        coordinates: { latitude: -29.1183, longitude: 26.2249 },
        epsg_code: 4148,
      },
      crop_profile: {
        species: "White Maize",
        botanical_name: "Zea mays",
        phenological_stage: "Vegetative V6 Stage",
        area: 60,
        area_unit: "Hectares",
      },
      telemetry: {
        meteorological: {
          source: "SAWS / Open-Meteo",
          temperature_c: 24.8,
          rainfall_48h_mm: 0.0,
          et0_daily_mm: 3.8,
          relative_humidity_pct: 42,
        },
        earth_observation: {
          platform: "Sentinel-2 + Landsat-9",
          current_ndvi: 0.64,
          canopy_trend: "stable",
          observation_timestamp: "2026-09-28T08:30:00Z",
        },
        soil_chemistry: {
          standard: "ARC-ISCW Land Type Survey",
          ph: 6.2,
          organic_carbon_pct: 0.72,
          nitrogen_kg_ha: 140,
          soil_texture_class: "Sandy Clay Loam",
        },
      },
      inferred_signals: {
        vegetation_stress: "moderate",
        irrigation_demand: "urgent",
        regenerative_horizon: "STAGE 1: In-situ moisture conservation furrowing",
      },
    },
  },
  {
    id: "china-henan",
    country: "China",
    countryCode: "CN",
    flag: "🇨🇳",
    institutionalAnchor: "CAAS (Chinese Academy of Agricultural Sciences)",
    location: "Xinxiang, Henan Basin",
    crop: "Winter Wheat / Maize Rotation",
    area: "8.0 Acres",
    crs: "CGCS2000 (EPSG:4490)",
    satellite: "Gaofen-1 + Sentinel-2",
    soilRef: "CAS Soil Science Institute",
    status: "Synchronized",
    latencyMs: 62,
    lastSync: "1 min ago",
    complianceScorePct: 100,
    cadsPacket: {
      $schema: "https://agrin.org/schema/v1/cads.json",
      schema_version: "CADS-v1.0.4",
      node_id: "CN-HA-XX-4029",
      node_country: "China",
      institutional_anchor: "CAAS Henan Agro-Ecological Station",
      cadastral_crs: "EPSG:4490",
      geographic_reference: {
        district: "Xinxiang",
        state_province: "Henan",
        coordinates: { latitude: 35.303, longitude: 113.9268 },
        epsg_code: 4490,
      },
      crop_profile: {
        species: "Winter Wheat",
        botanical_name: "Triticum aestivum",
        phenological_stage: "Jointing / Stem Elongation",
        area: 8.0,
        area_unit: "Acres",
      },
      telemetry: {
        meteorological: {
          source: "CMA / Open-Meteo",
          temperature_c: 19.4,
          rainfall_48h_mm: 6.0,
          et0_daily_mm: 2.7,
          relative_humidity_pct: 58,
        },
        earth_observation: {
          platform: "Gaofen-1 + Sentinel-2",
          current_ndvi: 0.76,
          canopy_trend: "increasing",
          observation_timestamp: "2026-09-28T02:10:00Z",
        },
        soil_chemistry: {
          standard: "CAS Alluvial Soil Grid",
          ph: 7.4,
          organic_carbon_pct: 1.15,
          nitrogen_kg_ha: 220,
          soil_texture_class: "Silt Loam",
        },
      },
      inferred_signals: {
        vegetation_stress: "low",
        irrigation_demand: "normal",
        regenerative_horizon: "STAGE 3: Wheat-Maize double-cropping residue retention",
      },
    },
  },
  {
    id: "russia-rostov",
    country: "Russia",
    countryCode: "RU",
    flag: "🇷🇺",
    institutionalAnchor: "Dokuchaev Soil Science Institute",
    location: "Rostov-on-Don Black Earth Zone",
    crop: "Spring Barley (Hordeum vulgare)",
    area: "450 Hectares",
    crs: "PZ-90 (EPSG:4115)",
    satellite: "Sentinel-2 + Meteor-M",
    soilRef: "Dokuchaev Chernozem Profile",
    status: "Operational",
    latencyMs: 83,
    lastSync: "8 mins ago",
    complianceScorePct: 100,
    cadsPacket: {
      $schema: "https://agrin.org/schema/v1/cads.json",
      schema_version: "CADS-v1.0.4",
      node_id: "RU-RO-RST-1044",
      node_country: "Russia",
      institutional_anchor: "Dokuchaev Agro-Chemistry Hub",
      cadastral_crs: "EPSG:4115",
      geographic_reference: {
        district: "Rostov-on-Don",
        state_province: "Rostov Oblast",
        coordinates: { latitude: 47.2357, longitude: 39.7015 },
        epsg_code: 4115,
      },
      crop_profile: {
        species: "Spring Barley",
        botanical_name: "Hordeum vulgare",
        phenological_stage: "Tillering",
        area: 450,
        area_unit: "Hectares",
      },
      telemetry: {
        meteorological: {
          source: "Roshydromet / Open-Meteo",
          temperature_c: 16.8,
          rainfall_48h_mm: 12.0,
          et0_daily_mm: 2.1,
          relative_humidity_pct: 69,
        },
        earth_observation: {
          platform: "Sentinel-2 + Meteor-M",
          current_ndvi: 0.68,
          canopy_trend: "increasing",
          observation_timestamp: "2026-09-27T09:20:00Z",
        },
        soil_chemistry: {
          standard: "Dokuchaev Chernozem Baseline",
          ph: 7.1,
          organic_carbon_pct: 3.42,
          nitrogen_kg_ha: 380,
          soil_texture_class: "Deep Chernozem Clay Loam",
        },
      },
      inferred_signals: {
        vegetation_stress: "low",
        irrigation_demand: "delay",
        regenerative_horizon: "STAGE 4: Chernozem carbon conservation & zero-tillage",
      },
    },
  },
];
